### ISSUE TITLE
Implement SASS Linter To Set Guidelines For Our Styles

### ISSUE THREAD

**Issue by asantos3026** [GuildCrafts/dragonboard-frontend#33]

**Comment by asantos3026** [comment]
- [SASS Linter Node](https://www.npmjs.com/package/sass-lint)
- [SASS Guidelines](http://cssguidelin.es/)

**Comment by jrob8577** [comment]
Closing, want to try CSS in JS (as described by gaearon in https://github.com/facebookincubator/create-react-app/issues/78)
